# Generated by Django 3.2.5 on 2021-08-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=30)),
                ('back', models.CharField(max_length=30)),
                ('adult', models.CharField(max_length=20)),
                ('children', models.CharField(max_length=20)),
                ('travelClass', models.CharField(max_length=20)),
            ],
        ),
    ]
